<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>DetectImg</name>
   <tag></tag>
   <elementGuidId>9c72cc7f-8936-4cea-89ef-f52e98448d2c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//nz-header/div[1]/div[2]/img[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//nz-header/div[1]/div[2]/img[1]</value>
   </webElementProperties>
</WebElementEntity>
