<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>clickOneInWindow</name>
   <tag></tag>
   <elementGuidId>4c7755e7-3ce2-4997-a209-fde76b004e2d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//header/div[1]/div[1]/div[2]/ul[1]/li[3]/a[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//header/div[1]/div[1]/div[2]/ul[1]/li[3]/a[1]</value>
   </webElementProperties>
</WebElementEntity>
