<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>PagiNextbtn</name>
   <tag></tag>
   <elementGuidId>16c17939-c1aa-4d6e-9cb2-323ce86db39a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@id='example_paginate']//a[@id='example_next']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@id='example_paginate']//a[@id='example_next']</value>
   </webElementProperties>
</WebElementEntity>
